# Generated by Django 4.1.3 on 2022-12-02 13:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_booklibrary_short_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videomessage',
            name='date_posted',
            field=models.DateField(default=datetime.date(2022, 12, 2)),
        ),
    ]
