# Generated by Django 4.1.3 on 2022-12-02 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_videomessage_date_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videomessage',
            name='date_posted',
            field=models.DateField(auto_now_add=True),
        ),
    ]
