# Generated by Django 4.1.3 on 2022-12-02 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_videomessage_date_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='videomessage',
            name='video_id',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
