# Generated by Django 4.1.3 on 2022-12-02 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_videomessage_video_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videomessage',
            options={'ordering': ['-date_posted']},
        ),
    ]
