# Generated by Django 4.1.3 on 2022-12-02 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_videomessage_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videomessage',
            options={'ordering': ['date_posted']},
        ),
    ]
