# Generated by Django 4.1.3 on 2022-12-05 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_videomessage_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='booklibrary',
            name='pdf',
            field=models.FileField(null=True, upload_to='BookLIbrary/PDf'),
        ),
        migrations.AlterField(
            model_name='booklibrary',
            name='cover_page',
            field=models.ImageField(upload_to='BooksLibrary/CoverPage'),
        ),
    ]
