# Generated by Django 4.1.3 on 2022-12-05 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_booklibrary_pdf_alter_booklibrary_cover_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booklibrary',
            name='pdf',
            field=models.FileField(default='dfadf.pdf', upload_to='BookLIbrary/PDf'),
        ),
    ]
