# Generated by Django 4.1.3 on 2022-12-05 10:41

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_booklibrary_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booklibrary',
            name='pdf',
            field=models.FileField(upload_to='BookLIbrary/PDf', validators=[main.models.validate_file]),
        ),
    ]
