# Generated by Django 4.1.3 on 2022-12-06 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_prayerrequest_alter_booklibrary_cover_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletterusers',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
